name: github-repo-stats

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repositories to generate reports for.
        statsRepo: ['ArrowElectronics/data-storm-daq', 'ArrowElectronics/10BASE-T1L-MC', 'ArrowElectronics/BMCU', 'ArrowElectronics/Reconfigurable-Industrial-Robotics-Platform', 'ArrowElectronics/Robotics_AMR']
      fail-fast: false
      max-parallel: 1
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.TEMP_TOKEN }}
